# -*- coding: utf-8 -*-
"""dio_etl

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDXElvDU6ZZdN8uSjQsog9a_Jg1152ge

## **E**xtract
"""

# !pip install openai

import pandas as pd
import openai
from time import sleep

df = pd.read_csv('pessoas.csv', sep=';')
#print(df) #Há alguns NaNs no dataframe

def validade_person(person): #será usado pra validar a pessoa no laço
    return not person.isna().any()

# Substitua o texto TODO por sua API Key da OpenAI, ela será salva como uma variável de ambiente.
openai_api_key = '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'


openai.api_key = openai_api_key

def generate_book_recommendation(person):
  prompt = f"""recomende 3 livros, sabendo que sou do sexo {person["Sexo"]}, tenho {person["Idade"]} e
  minha principal ocupação é ser {person["Ocupacao"]}."""
  
  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
      {
          "role": "system",
          "content": """Você é a IA da amazon, que tem como objetivo
          recomendar livros que as pessoas tenham altas chances de comprar.
          Não imforme mais nada além do nome e autor dos livros"""
      },
      {
          "role": "user",
          "content": prompt
      }
    ]
  )
  return completion.choices[0].message.content.strip('\"')

end = "-"*40
recomDict = {}
for person in range(len(df)):
    if validade_person(df.loc[person]):
        recommendation = generate_book_recommendation(df.loc[person])
        recomDict.update({df.loc[person]["Nome"]:recommendation})
        #print(df.loc[person]["Nome"],"\n",recommendation,end="\n"+end+"\n")
        sleep(20) #A API me deu um limite de 3 requisições por minuto

# Trata a resposta do chatGPT, fazendo cada tíulo de livro ser um objeto de um lista

for key in recomDict:
    temp = recomDict[key]
    temp = ''.join([i for i in temp if not i.isdigit()]).replace('.','').split('\n')
    recomDict[key] = temp


# Salva os resultados em um csv
df2 = df.copy()
print(recomDict)
recomdf = pd.DataFrame(recomDict.items(),columns=['Nome','Recomendacoes'])
recomdf.to_csv('recomendacoes.csv', index=False)

